function b=PRINTDEMOFIGURES
%PRINTDEMOFIGURES Signal function to print demo figures to file.
%
%   B=PRINTDEMOFIGURES returns whether any figures generated by the demo
%   programs should be written to disk. Used for generating the manual.

% $Id$

b=false;
